### ISSUE TITLE
Not an issue. Help with transparency

### ISSUE THREAD

**Issue by QNetITQ** [bpwned/protovibrant#4]
Hi. I want to include transparency in my style, but I don't have a real mac. Can you check my styles for transparency if I send them to you?

**Comment by bpwned** [comment]
I can try but I currently don't have much time to help you debug it if it doesn't work.

**Comment by QNetITQ** [comment]
Just check if there is transparency or not. The system theme must be selected in the browser 
[Vibrancy Test.txt](https://github.com/bpwned/protovibrant/files/7006556/Vibrancy.Test.txt)

**Comment by bpwned** [comment]
Unfortunately it doesn't seem to work.

![Bildschirmfoto 2021-08-18 um 12 50 19](https://user-images.githubusercontent.com/446744/129885649-322ee072-9fe4-4d9b-9e78-d66c65c3ccff.png)

**Comment by QNetITQ** [comment]
Please check these 
[Vibrancy Test 2.txt](https://github.com/bpwned/protovibrant/files/7006683/Vibrancy.Test.2.txt)
[Vibrancy Test 3.txt](https://github.com/bpwned/protovibrant/files/7006684/Vibrancy.Test.3.txt)

**Comment by bpwned** [comment]
I can't see any transparency/vibrancy with these either.

**Comment by bpwned** [comment]
What do you expect to be the outcome?

**Comment by QNetITQ** [comment]
There is no chance. Thanks for the help
