### ISSUE TITLE
[feature idea] Make the nav bar and toolbars optionally translucent too?

### ISSUE THREAD

**Issue by Tnings** [bpwned/protovibrant#5]

**Comment by bpwned** [comment]
I thought about it but right now I don't really have the time to find out how to do it. But I'm open to it if you want to have a look and give me some pointers.

**Comment by Tnings** [comment]
hmm I'll take a look into it, if I find anything I'll say it here!

**Comment by Tnings** [comment]
<img width="1440" alt="CleanShot 2021-08-19 at 10 53 43@2x" src="https://user-images.githubusercontent.com/55812511/130119613-a5bfac9b-2c1c-49bc-af17-d8c34219ef58.png">

I made it work! The menubar + bookmark toolbar are comment-out-able.

The tab style I use is from Simplify, and can be removed I just find that it looks better.

**Comment by bpwned** [comment]
Good job, that looks really great. How about you publish that yourself on https://firefoxcss-store.github.io/? I think it deserves beings its own entry.

**Comment by bpwned** [comment]
https://github.com/Tnings/MacosVibrant
